all:
  hosts:
    control_node:
      ansible_host: 172.31.29.115
    node1:
      ansible_host: 172.31.21.32
    node2:
      ansible_host: 172.31.25.69

  children:
    master_nodes: # This is a group of hosts
      hosts:
        control_node:
    worker_nodes:
      hosts:
        node1:
        node2:
    servers: # This is a group of groups
      children:
        master_nodes:
        worker_nodes:
      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ../clientkey.pem