all:
  hosts:
    control_node:
      ansible_user: ubuntu
      ansible_host: 172.31.29.115
      ansible_ssh_private_key_file: ../clientkey.pem
    node1:
      ansible_user: ubuntu
      ansible_host: 172.31.21.32
      ansible_ssh_private_key_file: ../clientkey.pem
    node2:
      ansible_user: ubuntu
      ansible_host: 172.31.25.69
      ansible_ssh_private_key_file: ../clientkey.pem
    
